// BIO 40B — Blood (Hematology)
// 50-question multiple-choice bank.
// Each question: { id, topic, q, choices: [5 strings A–E], answer: 0-4 }
// answer index is 0-based: 0=A, 1=B, 2=C, 3=D, 4=E

const QUESTIONS = [
    { id: 1, topic: "Blood Composition",
      q: "What percentage of whole blood is composed of plasma?",
      choices: ["45%", "55%", "1%", "90%", "10%"], answer: 1 },
    { id: 2, topic: "Blood Composition",
      q: "After centrifuging, which blood component contains the cells responsible for immune function?",
      choices: ["Plasma", "Buffy coat", "Erythrocytes", "Hematocrit", "Water"], answer: 1 },
    { id: 3, topic: "Plasma Proteins",
      q: "Which plasma protein makes up about 60% of plasma proteins and is responsible for maintaining osmotic pressure?",
      choices: ["Alpha globulin", "Beta globulin", "Fibrinogen", "Albumin", "Gamma globulin"], answer: 3 },
    { id: 4, topic: "Blood Composition",
      q: "Which component of blood makes up the \"buffy coat\" along with platelets?",
      choices: ["Erythrocytes", "Leukocytes", "Plasma", "Albumin", "Electrolytes"], answer: 1 },
    { id: 5, topic: "Hemoglobin",
      q: "How many oxygen atoms can each hemoglobin molecule transport?",
      choices: ["1", "2", "4", "40", "400"], answer: 2 },
    { id: 6, topic: "Hemoglobin",
      q: "Oxygen binds directly to which portion of the hemoglobin molecule?",
      choices: ["Globin chain", "Amino acid", "Iron atom", "Mitochondria", "Cell membrane"], answer: 2 },
    { id: 7, topic: "Red Blood Cells",
      q: "Which characteristic of red blood cells primarily contributes to their significant oxygen-carrying capacity?",
      choices: ["They possess a spherical shape.", "They contain numerous mitochondria.", "They lack mitochondria.", "They contain myoglobin.", "They constantly divide."], answer: 2 },
    { id: 8, topic: "Anemia",
      q: "A patient with significantly low iron levels would most likely experience which of the following symptoms?",
      choices: ["Increased energy levels", "An increased white blood cell count", "An increase in fatigue", "Elevated body temperature", "Decreased blood viscosity"], answer: 2 },
    { id: 9, topic: "Hematopoiesis",
      q: "All formed elements of blood (erythrocytes, leukocytes, and platelets) arise from a common stem cell known as a:",
      choices: ["Megakaryocyte", "Macrophage", "Pluripotent stem cell (hemocytoblast)", "Reticulocyte", "Lymphoid stem cell"], answer: 2 },
    { id: 10, topic: "Erythropoietin",
      q: "What would be the expected physiological outcome of an overdose of the hormone erythropoietin (EPO)?",
      choices: ["Blood viscosity increases to dangerous levels.", "Oxygen-carrying capacity remains unchanged.", "Red blood cell counts drop completely.", "Blood viscosity levels decrease.", "White blood cell counts increase significantly."], answer: 0 },
    { id: 11, topic: "Erythropoietin",
      q: "Which response would occur naturally after traveling to a high altitude for two weeks?",
      choices: ["A surge in iron release from the liver.", "The kidneys secrete elevated amounts of erythropoietin.", "Blood levels of oxygen remain depressed forever.", "There would be no change in blood composition.", "The bone marrow would halt red blood cell production."], answer: 1 },
    { id: 12, topic: "Anemia",
      q: "If a patient has pernicious anemia, they have an inability to absorb which of the following?",
      choices: ["Iron", "Vitamin B12", "Folic acid", "Vitamin K", "Calcium"], answer: 1 },
    { id: 13, topic: "White Blood Cells",
      q: "An elevated neutrophil count is typically indicative of which of the following?",
      choices: ["An allergic reaction", "A parasitic infection", "An acute bacterial infection", "Normal health", "Viral mononucleosis"], answer: 2 },
    { id: 14, topic: "White Blood Cells",
      q: "Antihistamine medications would primarily counter the actions of which type of white blood cell?",
      choices: ["Eosinophils", "Basophils", "Lymphocytes", "Neutrophils", "Monocytes"], answer: 1 },
    { id: 15, topic: "Blood Disorders",
      q: "Leukemia is a general medical descriptor for which of the following disorders?",
      choices: ["Overproduction of abnormal leukocytes", "An abnormally low white blood cell count", "Overproduction of abnormal erythrocytes", "Elevated counts of normal neutrophils", "A deficiency in circulating platelets"], answer: 0 },
    { id: 16, topic: "Hemostasis",
      q: "Why do platelets NOT form plugs in healthy, undamaged blood vessels?",
      choices: ["Platelets are only formed after an injury occurs.", "Plugs do form constantly but are removed by macrophages.", "Platelets require contact with exposed collagen fibers to become sticky.", "Megakaryocytes form the plugs instead.", "Red blood cells block them from reaching the vessel walls."], answer: 2 },
    { id: 17, topic: "Anticoagulants",
      q: "An injectable heparin medication might be prescribed for a patient who:",
      choices: ["Has hemophilia", "Is at risk for an embolism", "Has thrombocytopenia", "Is deficient in a clotting factor", "Has a low red blood cell count"], answer: 1 },
    { id: 18, topic: "Blood Disorders",
      q: "Which bleeding disorder is caused by a condition that suppresses or destroys the red bone marrow?",
      choices: ["Thrombocytopenia", "Hemophilia A", "Hemophilia C", "Sickle-cell anemia", "Polycythemia vera"], answer: 0 },
    { id: 19, topic: "Blood Types",
      q: "Which naturally occurring antibodies (agglutinins) are present in the plasma of a person with B+ blood?",
      choices: ["Anti-A", "Anti-B", "Anti-A and Anti-Rh", "Anti-B and Anti-Rh", "Neither Anti-A nor Anti-B"], answer: 0 },
    { id: 20, topic: "Red Blood Cells",
      q: "What is the approximate lifespan of a healthy erythrocyte?",
      choices: ["2 days", "15 days", "35 days", "120 days", "365 days"], answer: 3 },
    { id: 21, topic: "White Blood Cells",
      q: "Which type of white blood cell comprises the largest percentage (60-70%) in a normal blood sample?",
      choices: ["Lymphocytes", "Neutrophils", "Monocytes", "Eosinophils", "Basophils"], answer: 1 },
    { id: 22, topic: "White Blood Cells",
      q: "Which leukocyte is an agranulocyte that travels into tissues and matures into a macrophage?",
      choices: ["Monocyte", "Lymphocyte", "Basophil", "Neutrophil", "Eosinophil"], answer: 0 },
    { id: 23, topic: "Hemostasis",
      q: "What chemical do normal endothelial cells release to inhibit platelet aggregation in undamaged vessels?",
      choices: ["Thrombin", "Histamine", "Prostacyclin and nitric oxide", "Fibrinogen", "Erythropoietin"], answer: 2 },
    { id: 24, topic: "Hemostasis",
      q: "During hemostasis, the very first step to occur when a blood vessel is damaged is:",
      choices: ["Coagulation", "Platelet plug formation", "Vascular spasm", "Fibrinolysis", "Clot retraction"], answer: 2 },
    { id: 25, topic: "Coagulation",
      q: "During the coagulation cascade, thrombin directly converts which inactive protein into its active mesh-forming state?",
      choices: ["Prothrombin into thrombin", "Fibrinogen into fibrin", "Plasminogen into plasmin", "Factor X into active Factor X", "Factor XII into active Factor XII"], answer: 1 },
    { id: 26, topic: "Fibrinolysis",
      q: "The process of breaking down a clot after a blood vessel has healed is known as:",
      choices: ["Clot retraction", "Coagulation", "Fibrinolysis", "Agglutination", "Vasoconstriction"], answer: 2 },
    { id: 27, topic: "Fibrinolysis",
      q: "Which enzyme is responsible for breaking down fibrin during clot dissolution?",
      choices: ["Plasmin", "Thrombin", "Renin", "Carbonic anhydrase", "Amylase"], answer: 0 },
    { id: 28, topic: "Blood Disorders",
      q: "What term describes a blood clot that develops and persists in an unbroken blood vessel?",
      choices: ["Embolus", "Thrombus", "Petechiae", "Macrocyte", "Reticulocyte"], answer: 1 },
    { id: 29, topic: "Blood Disorders",
      q: "Hemophilia A is the most common type of hemophilia and is caused by a deficiency in which clotting factor?",
      choices: ["Factor VII", "Factor VIII", "Factor IX", "Factor XI", "Factor XII"], answer: 1 },
    { id: 30, topic: "Blood Disorders",
      q: "Sickle-cell anemia is caused by a mutation involving exactly how many incorrect amino acids in the globin beta chain?",
      choices: ["One", "Four", "Ten", "50", "146"], answer: 0 },
    { id: 31, topic: "Blood Disorders",
      q: "Which of the following conditions is characterized by a hematocrit that may go as high as 80% due to bone marrow cancer?",
      choices: ["Secondary polycythemia", "Polycythemia vera", "Aplastic anemia", "Leukopenia", "Acute hemorrhagic anemia"], answer: 1 },
    { id: 32, topic: "White Blood Cells",
      q: "Which specific white blood cells are associated with responding to allergies and parasitic infections?",
      choices: ["Neutrophils", "Monocytes", "Eosinophils", "Basophils", "Lymphocytes"], answer: 2 },
    { id: 33, topic: "White Blood Cells",
      q: "Which type of lymphocyte develops into plasma cells and produces antibodies?",
      choices: ["T cells", "Natural killer (NK) cells", "Macrophages", "B cells", "Megakaryocytes"], answer: 3 },
    { id: 34, topic: "Blood Disorders",
      q: "What is the diagnostic platelet count threshold for thrombocytopenia?",
      choices: ["Less than 150,000/µl", "Less than 100,000/µl", "Less than 50,000/µl", "Less than 10,000/µl", "Less than 5,000/µl"], answer: 2 },
    { id: 35, topic: "Blood Disorders",
      q: "The appearance of petechiae (spontaneous, widespread hemorrhage spots) is a hallmark symptom of which disorder?",
      choices: ["Hemophilia", "Thrombocytopenia", "Leukemia", "Polycythemia", "Pernicious anemia"], answer: 1 },
    { id: 36, topic: "Coagulation",
      q: "Which ion is essential and required for the blood clotting cascade to proceed normally?",
      choices: ["Sodium (Na+)", "Potassium (K+)", "Calcium (Ca2+)", "Iron (Fe2+)", "Magnesium (Mg2+)"], answer: 2 },
    { id: 37, topic: "Coagulation",
      q: "The intrinsic pathway of coagulation is initiated when which factor is activated by exposed collagen?",
      choices: ["Factor X", "Hageman factor (Factor XII)", "Tissue thromboplastin (Factor III)", "Prothrombin", "Factor VIII"], answer: 1 },
    { id: 38, topic: "Hemoglobin",
      q: "In carbon monoxide poisoning, carboxyhemoglobin forms. Carbon monoxide has how much more affinity for hemoglobin compared to oxygen?",
      choices: ["2 times", "10 times", "50 times", "100 times", "200 times"], answer: 4 },
    { id: 39, topic: "Red Blood Cells",
      q: "Which enzyme is found in the cytoplasm of red blood cells and converts carbon dioxide into bicarbonate?",
      choices: ["Urokinase", "Carbonic anhydrase", "Plasmin", "Thrombin", "Erythropoietin"], answer: 1 },
    { id: 40, topic: "Red Blood Cells",
      q: "Which of the following represents a normal adult red blood cell count?",
      choices: ["4.8 to 5.4 million/µL", "150,000 to 400,000/µL", "4,500 to 11,000/µL", "10 to 20 million/µL", "50,000 to 100,000/µL"], answer: 0 },
    { id: 41, topic: "Erythropoiesis",
      q: "The immediate precursor cell to a mature erythrocyte, which takes about 2 days to mature in the bloodstream, is called a:",
      choices: ["Proerythroblast", "Megakaryocyte", "Reticulocyte", "Hemocytoblast", "Myeloblast"], answer: 2 },
    { id: 42, topic: "Erythropoietin",
      q: "Erythropoietin (EPO), the hormone that regulates red blood cell production, is primarily produced by which organ?",
      choices: ["Liver", "Spleen", "Red bone marrow", "Kidneys", "Heart"], answer: 3 },
    { id: 43, topic: "Red Blood Cells",
      q: "What happens to the iron portion of hemoglobin when an old red blood cell is destroyed?",
      choices: ["It is converted into bilirubin.", "It is converted to biliverdin.", "It binds to transferrin and is reused.", "It is excreted in feces as stercobilin.", "It is broken down into amino acids."], answer: 2 },
    { id: 44, topic: "Anemia",
      q: "A patient suffering from a bleeding ulcer is most likely to develop which specific type of anemia?",
      choices: ["Acute hemorrhagic anemia", "Chronic hemorrhagic anemia", "Aplastic anemia", "Renal anemia", "Iron-deficiency anemia"], answer: 1 },
    { id: 45, topic: "Anemia",
      q: "The production of microcytes (small, pale red blood cells) is characteristic of which condition?",
      choices: ["Pernicious anemia", "Sickle-cell anemia", "Iron-deficiency anemia", "Aplastic anemia", "Hemorrhagic anemia"], answer: 2 },
    { id: 46, topic: "White Blood Cells",
      q: "Which class of blood cells normally lives for only a few hours to a few days?",
      choices: ["Erythrocytes", "White blood cells", "Platelets", "Reticulocytes", "Megakaryocytes"], answer: 1 },
    { id: 47, topic: "Blood Disorders",
      q: "An abnormally low white blood cell count, often induced by anticancer drugs or glucocorticoids, is called:",
      choices: ["Leukemia", "Leukocytosis", "Leukopenia", "Polycythemia", "Thrombocytopenia"], answer: 2 },
    { id: 48, topic: "Fibrinolysis",
      q: "Tissue plasminogen activator (tPA) is a substance that normally functions to:",
      choices: ["Initiate the extrinsic clotting pathway", "Convert plasminogen into plasmin for clot dissolution", "Trigger vascular spasm", "Stimulate the production of platelets", "Activate Factor X"], answer: 1 },
    { id: 49, topic: "Blood Types",
      q: "Which blood type is characterized by possessing BOTH A and B antigens on its red blood cells, but neither anti-A nor anti-B antibodies in its plasma?",
      choices: ["Type A", "Type B", "Type AB", "Type O", "Type O-negative"], answer: 2 },
    { id: 50, topic: "Blood Types",
      q: "If a person's untreated blood clumps (agglutinates) when exposed to Anti-B serum, but does NOT clump when exposed to Anti-A serum, what is their blood type?",
      choices: ["Type A", "Type B", "Type AB", "Type O", "Type Rh-positive"], answer: 1 },
];
